# Generated by Django 4.0.3 on 2022-05-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='logo.jpg', upload_to=''),
        ),
    ]
