# Generated by Django 4.0.3 on 2022-05-31 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0006_alter_profile_bio_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='mews.jpg', upload_to=''),
        ),
    ]
