# Generated by Django 4.0.3 on 2022-06-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0012_comentarios_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-timestamp']},
        ),
    ]
