# Generated by Django 4.0.3 on 2022-06-05 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0013_alter_comentarios_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comentarios',
        ),
    ]
