# Generated by Django 4.0.3 on 2022-06-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0016_comment_delete_comentarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
