# Generated by Django 4.0.3 on 2022-06-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0019_remove_comment_approved_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=False),
        ),
    ]
