# Generated by Django 4.1.2 on 2023-03-18 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controlador', '0023_remove_comment_approved_comment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_date',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
    ]
